"use client";
import { useEffect, useState } from "react";
type Media={id:string;name:string;url:string;alt_text:string;mime_type:string;width:number|null;height:number|null;transparent_background:boolean;kind:string;active:boolean};
export default function MediaManager(){const[media,setMedia]=useState<Media[]>([]),[file,setFile]=useState<File|null>(null),[alt,setAlt]=useState(""),[name,setName]=useState(""),[url,setUrl]=useState(""),[notice,setNotice]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState<"upload"|"url">("upload");
async function load(){const r=await fetch("/api/admin/media",{cache:"no-store"}),d=await r.json().catch(()=>null);if(!r.ok)throw Error(d?.error||"Unable to load media.");setMedia(Array.isArray(d.media)?d.media:[])}useEffect(()=>{load().catch(e=>setError(e.message))},[]);
async function upload(){if(!file){setError("Choose an image first.");return}setBusy(true);setError("");setNotice("");const fd=new FormData();fd.append("file",file);fd.append("alt_text",alt);const r=await fetch("/api/admin/media/upload",{method:"POST",body:fd}),d=await r.json().catch(()=>null);if(!r.ok){setError(d?.error||"Upload failed.");setBusy(false);return}setNotice("Image uploaded to the media library.");setFile(null);setAlt("");setBusy(false);await load()}
async function addUrl(){if(!name.trim()||!url.trim()){setError("Enter a name and image URL.");return}setBusy(true);setError("");const r=await fetch("/api/admin/media",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,url,alt_text:alt,mime_type:"image/*",kind:"image",transparent_background:false,active:true})}),d=await r.json().catch(()=>null);if(!r.ok){setError(d?.error||"Unable to add image.");setBusy(false);return}setNotice("Image added to the media library.");setName("");setUrl("");setAlt("");setBusy(false);await load()}
async function toggle(m:Media){const r=await fetch("/api/admin/media",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:m.id,active:!m.active})});if(r.ok)await load()}
return <div className="mt-8 space-y-5">{notice&&<p className="rounded-2xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{notice}</p>}{error&&<p className="rounded-2xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}
<section className="rounded-3xl border border-black/10 bg-white/60 p-5 sm:p-7"><div><p className="text-[10px] font-black tracking-[.18em] text-[#315233]">MEDIA LIBRARY</p><h2 className="mt-1 text-2xl font-semibold">Images for the whole site</h2><p className="mt-2 text-sm text-black/50">Upload transparent PNG/WebP/AVIF artwork, or register an existing image URL for use across homepage, pages and products.</p></div><div className="mt-6 flex gap-2"><button type="button" onClick={()=>setTab("upload")} className={`rounded-full px-4 py-2 text-xs font-bold ${tab==="upload"?"bg-[#202d20] text-[#f4f5e9]":"bg-black/5"}`}>Upload</button><button type="button" onClick={()=>setTab("url")} className={`rounded-full px-4 py-2 text-xs font-bold ${tab==="url"?"bg-[#202d20] text-[#f4f5e9]":"bg-black/5"}`}>Add URL</button></div>{tab==="upload"?<div className="mt-5 grid gap-4 md:grid-cols-[1.2fr_1fr_auto] items-end"><label className="block"><span className="mb-1.5 block text-[10px] font-black uppercase tracking-[.16em] text-black/45">Image</span><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>setFile(e.target.files?.[0]||null)} className="block w-full rounded-2xl border border-black/10 bg-[#f4f5e9] p-3 text-sm"/></label><label className="block"><span className="mb-1.5 block text-[10px] font-black uppercase tracking-[.16em] text-black/45">Alt text</span><input value={alt} onChange={e=>setAlt(e.target.value)} className="h-11 w-full rounded-2xl border border-black/10 bg-[#f4f5e9] px-4 text-sm"/></label><button type="button" onClick={upload} disabled={busy} className="rounded-full bg-[#ddf27a] px-5 py-3 text-sm font-bold text-[#202d20]">{busy?"Uploading…":"Upload image"}</button></div>:<div className="mt-5 grid gap-4 md:grid-cols-[1fr_1.4fr_1fr_auto] items-end"><label className="block"><span className="mb-1.5 block text-[10px] font-black uppercase tracking-[.16em] text-black/45">Name</span><input value={name} onChange={e=>setName(e.target.value)} className="h-11 w-full rounded-2xl border border-black/10 bg-[#f4f5e9] px-4 text-sm"/></label><label className="block"><span className="mb-1.5 block text-[10px] font-black uppercase tracking-[.16em] text-black/45">Image URL</span><input value={url} onChange={e=>setUrl(e.target.value)} className="h-11 w-full rounded-2xl border border-black/10 bg-[#f4f5e9] px-4 text-sm"/></label><label className="block"><span className="mb-1.5 block text-[10px] font-black uppercase tracking-[.16em] text-black/45">Alt text</span><input value={alt} onChange={e=>setAlt(e.target.value)} className="h-11 w-full rounded-2xl border border-black/10 bg-[#f4f5e9] px-4 text-sm"/></label><button type="button" onClick={addUrl} disabled={busy} className="rounded-full bg-[#ddf27a] px-5 py-3 text-sm font-bold text-[#202d20]">Add image</button></div>}</section>
<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{media.map(m=><article key={m.id} className="overflow-hidden rounded-3xl border border-black/10 bg-white/60"><div className="aspect-square bg-[#f4f5e9] p-4"><img src={m.url} alt={m.alt_text||m.name} className="h-full w-full object-contain"/></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">{m.name}</h3><p className="mt-1 text-xs text-black/45">{m.mime_type} {m.transparent_background?"· transparent":""}</p></div><button type="button" onClick={()=>toggle(m)} className="text-xs font-bold text-[#315233]">{m.active?"Visible":"Hidden"}</button></div><p className="mt-2 break-all text-[11px] text-black/40">{m.url}</p></div></article>)}</div></div>}
