"use client";
import { useEffect, useState } from "react";

type Block = { type: "heading" | "paragraph"; text: string };
type Page = { id?: string; slug: string; title: string; excerpt: string; content: Block[]; hero_image_url?: string | null; status: "draft" | "published"; published_at?: string | null; sort_order: number };
const empty: Page = { slug: "", title: "", excerpt: "", content: [{ type: "paragraph", text: "" }], hero_image_url: null, status: "draft", sort_order: 0 };
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-1.5 block text-[10px] font-black uppercase tracking-[.16em] text-black/45">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="h-11 w-full rounded-2xl border border-black/10 bg-[#f4f5e9] px-4 text-sm outline-none focus:border-black/25"/></label>}
export default function PagesManager(){
 const [pages,setPages]=useState<Page[]>([]),[editing,setEditing]=useState<Page|null>(null),[notice,setNotice]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 async function load(){const r=await fetch("/api/admin/pages",{cache:"no-store"});const d=await r.json().catch(()=>null);if(!r.ok)throw Error(d?.error||"Unable to load pages.");setPages(Array.isArray(d.pages)?d.pages:[])}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 function updateBlock(i:number,key:"type"|"text",value:string){if(!editing)return;const blocks=[...editing.content];blocks[i]={...blocks[i],[key]:value};setEditing({...editing,content:blocks})}
 async function save(){if(!editing)return;setSaving(true);setError("");setNotice("");const method=editing.id?"PATCH":"POST";const body=editing.id?{...editing}:{...editing};const r=await fetch("/api/admin/pages",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok){setError(d?.error||"Unable to save page.");setSaving(false);return;}setNotice(editing.id?"Page saved.":"Page created.");setEditing(null);setSaving(false);await load()}
 async function setStatus(page:Page,status:"draft"|"published"){const r=await fetch("/api/admin/pages",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:page.id,status})});const d=await r.json().catch(()=>null);if(!r.ok){setError(d?.error||"Unable to update status.");return;}await load()}
 return <div className="mt-8 space-y-5">{notice&&<p className="rounded-2xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{notice}</p>}{error&&<p className="rounded-2xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}
 <section className="rounded-3xl border border-black/10 bg-white/60 p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-black tracking-[.18em] text-[#315233]">PAGES / JOURNAL</p><h2 className="mt-1 text-2xl font-semibold">Editorial content</h2><p className="mt-2 text-sm text-black/50">Create pages and journal articles, save drafts and publish them when ready.</p></div><button type="button" onClick={()=>setEditing({...empty,content:[{type:"paragraph",text:""}]})} className="rounded-full bg-[#202d20] px-5 py-2.5 text-xs font-bold text-[#f4f5e9]">+ New page</button></div></section>
 {editing&&<section className="rounded-3xl border border-black/10 bg-white/70 p-5 sm:p-7"><div className="flex items-center justify-between gap-3 border-b border-black/10 pb-5"><h2 className="text-xl font-semibold">{editing.id?"Edit page":"New page"}</h2><div className="flex gap-2"><button type="button" onClick={()=>setEditing(null)} className="rounded-full border border-black/15 px-4 py-2 text-xs font-bold">Cancel</button><button type="button" onClick={save} disabled={saving} className="rounded-full bg-[#ddf27a] px-5 py-2 text-xs font-bold text-[#202d20]">{saving?"Saving…":"Save page"}</button></div></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Title" value={editing.title} onChange={v=>setEditing({...editing,title:v})}/><Field label="Slug" value={editing.slug} onChange={v=>setEditing({...editing,slug:v})}/><Field label="Excerpt" value={editing.excerpt} onChange={v=>setEditing({...editing,excerpt:v})}/><Field label="Hero image URL" value={editing.hero_image_url||""} onChange={v=>setEditing({...editing,hero_image_url:v||null})}/></div><div className="mt-5 flex flex-wrap items-center gap-3"><select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as Page["status"]})} className="h-11 rounded-2xl border border-black/10 bg-[#f4f5e9] px-4 text-sm"><option value="draft">Draft</option><option value="published">Published</option></select><Field label="Sort order" value={String(editing.sort_order)} onChange={v=>setEditing({...editing,sort_order:Number(v)||0})}/></div><div className="mt-6 space-y-3"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Content blocks</h3><button type="button" onClick={()=>setEditing({...editing,content:[...editing.content,{type:"paragraph",text:""}]})} className="rounded-full border border-black/15 px-4 py-2 text-xs font-bold">+ Add block</button></div>{editing.content.map((b,i)=><div key={i} className="rounded-2xl bg-[#f4f5e9] p-4"><div className="grid gap-3 md:grid-cols-[150px_1fr]"><select value={b.type} onChange={e=>updateBlock(i,"type",e.target.value)} className="h-11 rounded-xl border border-black/10 bg-white/60 px-3 text-sm"><option value="paragraph">Paragraph</option><option value="heading">Heading</option></select><textarea value={b.text} onChange={e=>updateBlock(i,"text",e.target.value)} className="min-h-24 rounded-xl border border-black/10 bg-white/60 px-3 py-3 text-sm outline-none" /></div></div>)}</div></section>}
 {pages.map(p=><article key={p.id||p.slug} className="rounded-3xl border border-black/10 bg-white/60 p-5 sm:p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-xl font-semibold">{p.title}</h3><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${p.status==="published"?"bg-emerald-100 text-emerald-800":"bg-black/10 text-black/45"}`}>{p.status}</span></div><p className="mt-1 text-sm text-black/45">/{p.slug}</p>{p.excerpt&&<p className="mt-2 text-sm text-black/55">{p.excerpt}</p>}</div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>setEditing({...p})} className="rounded-full border border-black/15 px-4 py-2 text-xs font-bold">Edit</button>{p.status==="published"?<button type="button" onClick={()=>setStatus(p,"draft")} className="rounded-full border border-black/15 px-4 py-2 text-xs font-bold">Unpublish</button>:<button type="button" onClick={()=>setStatus(p,"published")} className="rounded-full bg-[#ddf27a] px-4 py-2 text-xs font-bold text-[#202d20]">Publish</button>}</div></div></article>)}
 </div>;
}
